# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [14]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

insurance_df = pd.read_csv(url)

insurance_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [18]:

insurance_df.shape
#numero de columnas y filas

(4008, 11)

In [ ]:
insurance_df.columns
#nombres de columnas

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [20]:
insurance_df.dtypes
#tipo de datos de cada columna

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [21]:
insurance_df.info()
#informacion general del dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [25]:
insurance_df.describe().T
#estadisticas descriptivas de las columnas numericas

,count,mean,std,min,25%,50%,75%,max
Income,1071.0,39295.701214,30469.427060,0.000000,14072.000000,36234.000000,64631.0,99960.000000
Monthly Premium Auto,1071.0,193.234360,1601.190369,61.000000,68.000000,83.000000,109.5,35354.000000
Total Claim Amount,1071.0,404.986909,293.027260,0.382107,202.157702,354.729129,532.8,2893.239678

In [26]:
insurance_df.describe(include="all")

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
count,1071,1071,954,1071,1068,1071.000000,1071.000000,1071,1071,1071,1071.000000
unique,1071,8,5,6,1027,NaN,NaN,6,3,6,NaN
top,RB50392,Oregon,F,Bachelor,445811.34%,NaN,NaN,1/0/00,Personal Auto,Four-Door Car,NaN
freq,1,320,457,324,4,NaN,NaN,830,780,576,NaN
mean,NaN,NaN,NaN,NaN,NaN,39295.701214,193.234360,NaN,NaN,NaN,404.986909
std,NaN,NaN,NaN,NaN,NaN,30469.427060,1601.190369,NaN,NaN,NaN,293.027260
min,NaN,NaN,NaN,NaN,NaN,0.000000,61.000000,NaN,NaN,NaN,0.382107
25%,NaN,NaN,NaN,NaN,NaN,14072.000000,68.000000,NaN,NaN,NaN,202.157702
50%,NaN,NaN,NaN,NaN,NaN,36234.000000,83.000000,NaN,NaN,NaN,354.729129
75%,NaN,NaN,NaN,NaN,NaN,64631.000000,109.500000,NaN,NaN,NaN,532.800000
max,NaN,NaN,NaN,NaN,NaN,99960.000000,35354.000000,NaN,NaN,NaN,2893.239678

In [34]:
categorical_cols = insurance_df.describe(include= 'object').columns

In [36]:
for col in categorical_cols:
    print(f"columns: {col}")
    print(insurance_df[col].value_counts())

columns: Customer
Customer
RB50392    1
HJ15383    1
AO74776    1
HQ82233    1
OL72737    1
          ..
RO26085    1
ES57969    1
JK55587    1
RN97635    1
MY31220    1
Name: count, Length: 1071, dtype: int64
columns: ST
ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64
columns: GENDER
GENDER
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64
columns: Education
Education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64
columns: Customer Lifetime Value
Customer Lifetime Value
445811.34%     4
251459.20%     4
272535.64%     3
578018.22%     3
684615.03%     3
              ..
245357.08%     1
507566.27%     1
321497.94%     1
1227534.31%    1
899704.02%     1
Name: count, Length: 1027, dtype: int64
columns: Number of Open Complaints
Number of Open Complaints
1/0/00    830
1/1/00    138
1/2/00     50
1/3/00     34
1/4/00     13
1/5/00      6
Name: count, dtype: int64
columns: Policy Type
Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64
columns: Vehicle Class
Vehicle Class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

El dataset contiene información de clientes de seguros.
Incluye variables numéricas (Income, CLV, Monthly Premium Auto) y categóricas (Gender, Education, Policy Type).
Existen diferentes tipos de vehículos y pólizas.
Algunas variables muestran alta variabilidad (como Income o Total Claim Amount).
Se pueden realizar análisis de comportamiento del cliente y rentabilidad.

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [38]:
insurance_df["ST"]

0       Washington
1          Arizona
2           Nevada
3       California
4       Washington
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: ST, Length: 4008, dtype: object

In [ ]:
#Cuentas estados → ordenas de menor a mayor → tomas 5.
location_counts = insurance_df["ST"].value_counts()

top_5_less_common = location_counts.sort_values(ascending=True).head(5)

print(top_5_less_common)

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [49]:
insurance_df["Policy Type"]

0        Personal Auto
1        Personal Auto
2        Personal Auto
3       Corporate Auto
4        Personal Auto
             ...
4003               NaN
4004               NaN
4005               NaN
4006               NaN
4007               NaN
Name: Policy Type, Length: 4008, dtype: object

In [ ]:
#cuentas tipos de poliza --> buscas el mas frecuente
policy_counts = insurance_df["Policy Type"].value_counts()

most_sold_policy = policy_counts.idxmax()

print(policy_counts)
print("policy type with the highest number of policies sold:")
print(most_sold_policy)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64
policy type with the highest number of policies sold:
Personal Auto

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [ ]:
#filtras dos tipos de poliza, calculas el ingreso promedio de cada uno y comparas
personal_auto_insurance_df = df.loc[df["Policy Type"] == "Personal Auto"]
corporate_auto_insurance_df = df.loc[df["Policy Type"] == "Corporate Auto"]

personal_auto_income_mean = personal_auto_insurance_df["Income"].mean()
corporate_auto_income_mean = corporate_auto_insurance_df["Income"].mean()

print("Average income - Personal Auto:", personal_auto_income_mean)
print("Average income - Corporate Auto:", corporate_auto_income_mean)

Average income - Personal Auto: 38180.69871794872
Average income - Corporate Auto: 41390.31196581197

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [57]:
print(df["Total Claim Amount"].describe())

q75 = df["Total Claim Amount"].quantile(0.75)
print(q75)

high_claim_df = df[df["Total Claim Amount"] > q75]

print(high_claim_df.shape)

print(high_claim_df.describe())

count    1071.000000
mean      404.986909
std       293.027260
min         0.382107
25%       202.157702
50%       354.729129
75%       532.800000
max      2893.239678
Name: Total Claim Amount, dtype: float64
532.8
(264, 11)
             Income  Monthly Premium Auto  Total Claim Amount
count    264.000000            264.000000          264.000000
mean   23677.344697            165.193182          782.228263
std    27013.483721            623.930992          292.751640
min        0.000000             63.000000          537.600000
25%        0.000000             99.000000          606.521741
50%    18807.000000            114.000000          679.597985
75%    42423.750000            133.250000          851.400000
max    99316.000000          10202.000000         2893.239678